---
title: "qPCR_analysis_pipeline"
author: "Sejun Kim"
date: '2022 3 2 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dir <-'your_data_path'
library(tidyverse)
```

# Data load

Before start, csv file format with result only available.

```{r}
# data load
data1 <- read_csv(paste0(dir, 'your_data_result'))

# pick actural results
data_total <- data1[41:nrow(data1),]
colnames(data_total) <- data1[40,]
write.csv(data_total, file=paste0(dir, 'qPCR_total_result.csv'))

# Use 3 columns to calculate
data <- data_total %>%
  dplyr::select(c('sample'=`Sample Name`, target=`Target Name`, ct_mean=`Ct Mean`)) %>%
  mutate(ct_mean=as.numeric(ct_mean)) %>%
  unique() %>%
  na.omit()

samples <- str_split_fixed(data$sample, '[0-9]$', 2)
data$sample <- samples[,1]

head(data)

write.csv(data, file=paste0(dir, 'qPCR_result_3_columns.csv'))
```

# calculate delta ct
```{r}
hk_gene <- data %>%
  filter(target == 'beta-actin') # use name of your house-keeping gene

deltact <- left_join(data, hk_gene, by = 'sample', suffix = c('', '.hk'))%>%
  dplyr::select(-target.hk) %>%
  mutate(delta_ct = ct_mean - ct_mean.hk)

# calculate delta delta ct and  foldchange, mean and sd
nt_data <- deltact %>%
  filter(sample == 'NT') %>% 
  group_by(target) %>%
  summarize(mean_of_dct_nt = mean(delta_ct))

ddct <- left_join(deltact, nt_data, by = 'target')  %>%
  mutate(ddct = delta_ct - mean_of_dct_nt, Foldchange = 2^(-ddct)) %>%
  na.omit() 


mean_sd <- ddct %>%
  group_by(target, sample) %>%
  summarize(mean_of_Fc = mean(Foldchange), sd_of_Fc = sd(Foldchange))


```

# draw a plot

```{r}

qpcr_mean_plot <- ggplot(mean_sd, aes(x = sample, y = mean_of_Fc, fill = target)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~target) +
  geom_errorbar(aes(ymin = mean_of_Fc - sd_of_Fc, ymax = mean_of_Fc + sd_of_Fc)) +
  theme_bw()

qpcr_mean_plot

ggsave(qpcr_mean_plot, file = paste0(dir, 'qpcr_mean_plot.png'))
```



# If you want to draw specific targets and boxplot, template is below.


```{r}
# library(ggpubr)
# 
# # when I would like to check only LINC and MET
# ddct <- left_join(deltact, nt_data, by = 'target')  %>%
#   mutate(ddct = delta_ct - mean_of_dct_nt, Foldchange = 2^(-ddct)) %>%
#   na.omit(.) %>%
#   filter(target == 'LINC' | target == 'MET')
# 
# mean_sd <- ddct %>%
#   group_by(target, sample) %>%
#   summarize(mean_of_Fc = mean(Foldchange), sd_of_Fc = sd(Foldchange)) %>%
#   filter(target == 'LINC' | target == 'MET')
# 
# # to draw statistical test
# my_comparisons = list(c('LINC', 'LIP'),c('LINC','MET'),c('LINC', 'NT'),c('LINC', 'WT'),
#                       c('LIP', 'MET'),c('LIP', 'NT'), c('LIP', 'WT'),
#                       c('MET', 'NT'), c('MET', 'WT'), c('NT', 'WT'))
# 
# 
# boxplot <- ggplot(ddct, aes(x = sample, y = Foldchange, fill = target)) +
#   geom_boxplot() +
#   # facet_wrap(~target) +
#   # scale_y_continuous(limits = c(-1, 10)) +
#   theme_bw() +
#   stat_compare_means(comparisons = my_comparisons, label = 'p.signif', method = 'wilcox.test') 
# # t.test is only available for paramatric data (over 30 cases)
# 
# boxplot
# 
# 
# ggsave(boxplot, file = paste0(dir, 'qpcr_boxplot.png'))

```

